spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:~/test
    username: sa
  batch:
    initialize-schema: always
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
    show-sql: true
